[package]
name = "udp"
version = "0.10.0"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"]
license = "MIT"
description = "A lightweight and efficient Rust library for building UDP servers with request-response handling."
keywords = ["udp", "request", "response", "server", "network"]
repository = "https://github.com/ltpp-universe/udp.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github",
    "logs",
    "**/*.log"
]

[dependencies]
async-func = "0.1.8"
clonelicious = "1.0.5"
color-output = "6.4.3"
file-operation = "0.4.3"
hyperlane-log = "1.2.3"
lombok-macros = "1.8.1"
recoverable-spawn = "3.4.3"
recoverable-thread-pool = "2.0.11"
std-macro-extensions = "0.21.5"
tokio = { version = "1.44.1", features = ["full"] }
once_cell = "1.21.1"
simd-json = "0.14.3"
serde = "1.0.218"
serde_json = "1.0.140"
futures = "0.3.31"
server-manager = "3.0.11"
