[package]
name = "udp"
version = "0.0.1"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"]
license = "MIT"
description = "A lightweight and efficient Rust library for building UDP servers with request-response handling."
keywords = ["udp", "request", "response", "server", "network"]
repository = "https://github.com/ltpp-universe/udp.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github",
    "logs",
    "**/*.log"
]

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }