[package]
name = "udp"
version = "0.9.2"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"]
license = "MIT"
description = "A lightweight and efficient Rust library for building UDP servers with request-response handling."
keywords = ["udp", "request", "response", "server", "network"]
repository = "https://github.com/ltpp-universe/udp.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github",
    "logs",
    "**/*.log"
]

[dependencies]
async-func = "0.1.6"
clonelicious = "1.0.4"
color-output = "6.4.2"
file-operation = "0.4.2"
hyperlane-log = "1.2.2"
lombok-macros = "1.8.0"
recoverable-spawn = "3.4.2"
recoverable-thread-pool = "2.0.10"
std-macro-extensions = "0.21.4"
tokio = { version = "1.43.0", features = ["full"] }
once_cell = "1.20.3"
simd-json = "0.14.3"
serde = "1.0.218"
serde_json = "1.0.140"
futures = "0.3.31"
server-manager = "3.0.10"
